AllCops:
  TargetRubyVersion: 3.4
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - "tmp/**/*"

Lint/ConstantResolution:
  Enabled: true

Metrics:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: nested

Style/Documentation:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: true
