AllCops:
  TargetRubyVersion: 3.4
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - "tmp/**/*"

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Lint/ConstantResolution:
  Enabled: true

Metrics:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames: [_, e]

Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: nested

Style/Documentation:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: true

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: diff_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: diff_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: diff_comma
